apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
    lab: lab2
spec:
  # Используем секрет, который вы создали ранее
  imagePullSecrets:
    - name: ghcr-secret
  containers:
    - name: go-app
      # Замените ВАШ_ЛОГИН на ваш реальный логин GitHub
      image: ghcr.io/dr0p-database/containers-lab-1/app:latest
      ports:
        - containerPort: 8080
      # env:
      #   - name: DB_HOST
      #     value: "postgres-service"
      #   - name: DB_PORT
      #     value: "5432"